<?php

// PHP 5.4 constants

define('PHPCOMPAT_JSON_NUMERIC_CHECK',      32);
define('PHPCOMPAT_JSON_UNESCAPED_SLASHES',  64);
define('PHPCOMPAT_JSON_PRETTY_PRINT',      128);
define('PHPCOMPAT_JSON_UNESCAPED_UNICODE', 256);

